#!/usr/bin/env python
"""Reject writing patterns that make repository text read as machine output."""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

BANNED_WORDS = (
    "comprehensive",
    "robust",
    "seamless",
    "seamlessly",
    "leverage",
    "streamline",
    "elegant",
    "powerful",
    "cutting-edge",
    "best-in-class",
    "delve",
    "crucial",
    "vital",
    "unlock",
    "empower",
    "harness",
    "journey",
)

BANNED_PHRASES = (
    "it's worth noting",
    "keep in mind",
    "in today's fast-paced",
    "at its core",
    "deep dive",
)

# co-author and attribution trailers, commit messages only
BANNED_TRAILERS = (
    "generated with",
    "co-authored-by",
)

# the checker is the one place these characters are allowed to appear as
# literals. scripts/ is deliberately not in the prose check's file list.
DASHES = {"—": "em dash", "–": "en dash"}
CURLY = dict.fromkeys(["‘", "’", "“", "”"], "curly quote")

# emoji blocks, dingbats, misc symbols, arrows, and the variation selector
# that turns a plain glyph into an emoji presentation
EMOJI = re.compile("[\U0001f000-\U0001faff☀-➿⬀-⯿️]")

CONVENTIONAL = re.compile(
    r"^(feat|fix|docs|test|chore|ci|refactor|perf|build|revert)"
    r"(\([a-z0-9._/-]+\))?!?: \S"
)

SUBJECT_MAX = 72


def _char_problems(text: str) -> list[tuple[int, str]]:
    """Find dashes, curly quotes and emoji, returning (line number, message)."""
    found: list[tuple[int, str]] = []
    for lineno, line in enumerate(text.splitlines(), start=1):
        for char, name in {**DASHES, **CURLY}.items():
            if char in line:
                found.append((lineno, f"{name} ({char!r})"))
        match = EMOJI.search(line)
        if match:
            found.append((lineno, f"emoji ({match.group()!r})"))
    return found


def _word_problems(text: str) -> list[tuple[int, str]]:
    found: list[tuple[int, str]] = []
    for lineno, line in enumerate(text.splitlines(), start=1):
        lowered = line.lower()
        for word in BANNED_WORDS:
            if re.search(rf"\b{re.escape(word)}\b", lowered):
                found.append((lineno, f"banned word: {word}"))
        for phrase in BANNED_PHRASES:
            if phrase in lowered:
                found.append((lineno, f"banned phrase: {phrase}"))
    return found


def check_prose(path: Path) -> list[str]:
    text = path.read_text(encoding="utf-8")
    problems = _char_problems(text) + _word_problems(text)
    return [f"{path}:{lineno}: {msg}" for lineno, msg in sorted(problems)]


def _strip_comments(raw: str) -> str:
    """Drop git's comment lines and everything below the scissors marker."""
    lines: list[str] = []
    for line in raw.splitlines():
        if line.startswith("# ------------------------ >8"):
            break
        if line.startswith("#"):
            continue
        lines.append(line)
    return "\n".join(lines).strip()


def check_commit_message(raw: str, label: str) -> list[str]:
    message = _strip_comments(raw)
    if not message:
        return [f"{label}: empty commit message"]

    problems = [f"{label}:{n}: {m}" for n, m in _char_problems(message)]
    problems += [f"{label}:{n}: {m}" for n, m in _word_problems(message)]

    lowered = message.lower()
    for trailer in BANNED_TRAILERS:
        if trailer in lowered:
            problems.append(f"{label}: attribution trailer: {trailer}")

    subject = message.splitlines()[0]

    # merges, reverts and autosquash markers are generated by git itself
    if subject.startswith(("Merge ", "Revert ", "fixup!", "squash!")):
        return problems

    if len(subject) > SUBJECT_MAX:
        problems.append(f"{label}: subject is {len(subject)} chars, max {SUBJECT_MAX}")
    if subject.endswith("."):
        problems.append(f"{label}: subject ends with a period")
    if not CONVENTIONAL.match(subject):
        problems.append(
            f"{label}: subject is not 'type(scope): summary' with a known type"
        )
    else:
        summary = subject.split(": ", 1)[1]
        # an acronym like DST or a path is fine, a capitalised sentence is not
        if summary[0].isupper() and not summary.split()[0].isupper():
            problems.append(f"{label}: summary should not start with a capital")

    if len(message.splitlines()) > 1 and message.splitlines()[1].strip():
        problems.append(f"{label}: no blank line between subject and body")

    return problems


def _default_paths() -> list[Path]:
    paths = [Path("README.md")]
    paths += sorted(Path("docs").rglob("*.md"))
    return [p for p in paths if p.exists()]


def _range_messages(rev_range: str) -> list[tuple[str, str]]:
    out = subprocess.run(
        ["git", "log", "--format=%H%x1f%B%x1e", rev_range],
        capture_output=True,
        text=True,
        encoding="utf-8",
        check=True,
    ).stdout
    messages: list[tuple[str, str]] = []
    for record in out.split("\x1e"):
        if not record.strip():
            continue
        sha, body = record.strip().split("\x1f", 1)
        messages.append((sha[:8], body))
    return messages


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("paths", nargs="*", type=Path)
    parser.add_argument("--commit-msg", action="store_true")
    parser.add_argument("--git-range", help="check commit subjects in a revision range")
    args = parser.parse_args()

    problems: list[str] = []

    if args.git_range:
        for sha, body in _range_messages(args.git_range):
            problems += check_commit_message(body, sha)
    elif args.commit_msg:
        for path in args.paths:
            problems += check_commit_message(
                path.read_text(encoding="utf-8"), str(path)
            )
    else:
        for path in args.paths or _default_paths():
            problems += check_prose(path)

    for problem in problems:
        print(problem, file=sys.stderr)
    return 1 if problems else 0


if __name__ == "__main__":
    raise SystemExit(main())
