#!/usr/bin/env python
"""Write the local compose secrets if they are not there already."""

from __future__ import annotations

import argparse
import base64
import os
from pathlib import Path

# Kept out of .env, which holds the entso-e and rte tokens. Compose reads .env
# automatically for interpolation, and putting api tokens in the same namespace
# as container config is how one of them ends up in a container by accident.
TARGET = Path(".env.docker")

KEYS = ("AIRFLOW_FERNET_KEY", "AIRFLOW_JWT_SECRET")


def generate() -> dict[str, str]:
    """A fernet key is 32 random bytes, url-safe base64 encoded."""
    return {name: base64.urlsafe_b64encode(os.urandom(32)).decode() for name in KEYS}


def render(values: dict[str, str]) -> str:
    header = (
        "# Local development only. Generated by scripts/dev_env.py and\n"
        "# gitignored. Delete this file and rerun make env to rotate.\n"
    )
    return header + "".join(f"{name}={value}\n" for name, value in values.items())


def write_if_missing(path: Path) -> bool:
    """True when a file was written, False when one was already there."""
    if path.exists():
        return False
    path.write_text(render(generate()), encoding="utf-8")
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--path", type=Path, default=TARGET)
    args = parser.parse_args()

    if write_if_missing(args.path):
        print(f"{args.path} written")
    else:
        print(f"{args.path} already exists, left alone")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
